### ISSUE TITLE
Rimworld 1.1

### ISSUE THREAD

**Issue by godofdream** [Alexis-Grimm/Un-Limited#1]
Rimworld 1.1 is in preview state and some mods were already updated.
I would love to see your mod on Version 1.1

**Comment by Alexis-Grimm** [comment]
Yes i will be updating when either the majority of mods that I need to enjoy rimworld update to 1.1 or 1.1 comes out of beta, until then I'm not playing rimworld and I'm not ready to update my mods. I might end up releasing an update before then, but I'm rather busy with school and such.

**Comment by Alexis-Grimm** [comment]
Updated to support 1.1
