### ISSUE TITLE
URL to the github F.A.Q. breaks because of "." at the end.

### ISSUE THREAD

**Issue by Thundercraft** [Alexis-Grimm/Un-Limited#11]
Because there is a "." (period) at the end of the link for your github F.A.Q., the link breaks and does not go there directly. (At least, the link to this F.A.Q. is broken on the Steam page. Also, when I paste the link into a document or something, it instantly and automatically breaks due to that period on the end.)

Perhaps you could rename that URL address to remove the periods, like so?
https://github.com/Alexis-Grimm/Un-Limited/wiki/FAQ

Just a thought.

**Comment by Alexis-Grimm** [comment]
Fixed, thanks!
