### ISSUE TITLE
cant find settings

### ISSUE THREAD

**Issue by JellyBean12914** [Alexis-Grimm/Un-Limited#14]
i feel like im going insane, i cant find this mod's settings anywhere, apparently they're supposed to be there but i cant find them under "Mod Settings" or "More mod settings", is this a bug of some kind or are they somewhere else?

**Comment by JellyBean12914** [comment]
found it out. turns out the most recent version available on github (1.2.7) is outdated and doesnt actually have settings yet. i'd now like to ask if the 2.0.0 version could be added to github?

**Comment by Alexis-Grimm** [comment]
I apologize, I'll get that fixed immediately, thanks for letting me know
