### ISSUE TITLE
Tend quality cap

### ISSUE THREAD

**Issue by Metallonality** [Alexis-Grimm/Un-Limited#16]
There's a cap on tend quality which stops on 200% by the post-process and uncapping it still turned on

![image](https://user-images.githubusercontent.com/81470079/194815329-de37afc9-6d7d-482e-b5a0-6f2526b6b1ad.png)
![image](https://user-images.githubusercontent.com/81470079/194815133-39e1e52f-87e1-4207-92c4-50f4758bbd26.png)

I'm not aware if any mod can return or force cap for it but there's no any issues like capping any other stat

Butchering and salvaging (aka mechanoid butchering) at the bottom turned off by me

**Comment by Alexis-Grimm** [comment]
Tend Qualities cap is a Post-Process curve which this mod won't remove, the only thing this mod does for Tend Quality is remove the cap on how much the capacities can improve it.
