### ISSUE TITLE
Blackscreen after startup

### ISSUE THREAD

**Issue by Babyknochen** [Alexis-Grimm/Un-Limited#20]
Right after the first loading screen when you would get into the menu I get a blackscreen. I cant see the logs so I cant send them in.

**Comment by Alexis-Grimm** [comment]
Would you be able to try to load the game with just Harmony, XMLExtensions, and Un-Limited? Or is that what you were doing?

**Comment by Babyknochen** [comment]
Sorry i forgot to comment again the update fixed my problem
