### ISSUE TITLE
Butchery and Mechanoid Disassembly efficiency capped at 100%

### ISSUE THREAD

**Issue by sza95** [Alexis-Grimm/Un-Limited#3]
Both butchering and mechanoid disassembly efficiency  are capped at 100% regardless health conditions that would allow those stats to be over the vanilla limit.
![imagen](https://user-images.githubusercontent.com/25018034/76536052-d197d400-6449-11ea-8d74-fa07713b8198.png)
![imagen](https://user-images.githubusercontent.com/25018034/76536067-d8264b80-6449-11ea-8272-4998faf9cd3f.png)

**Comment by sza95** [comment]
I don't know if double posting is wrong in Github but I found the problem after a quick digging in the game files, /Defs/Stats/Site_Pawns_WorkRecipes has both values for butchering and mechanoid disassembly efficiency, both have a max default value of 1, removing these lines of code uncaps them.
![imagen](https://user-images.githubusercontent.com/25018034/76536722-bb3e4800-644a-11ea-8ef8-ec30d682cf7c.png)
![imagen](https://user-images.githubusercontent.com/25018034/76536743-c002fc00-644a-11ea-9416-76956c27594a.png)

Hope it gets fixed in the next release, cheers.

**Comment by Alexis-Grimm** [comment]
Will fix with next release, probably over the weekend

**Comment by Alexis-Grimm** [comment]
Fixed in Version 1.2.2
