### ISSUE TITLE
Can you uncap Combat so this can be useful with level up

### ISSUE THREAD

**Issue by BUTTERSKY11** [Alexis-Grimm/Un-Limited#5]
I need the combat to be uncapped or capped at like 80%, like dodging and accuracy which has a cap at 50% so have a 200%+ moving or 200%+ sight does nothing, or with level up 200% agility does nothing to the cap even though it is listed. 

Also can you make a mod uncap damage resistance so I can make a one punch run where one punch is invulnerable

Please note level up works perfectly already with your mod, I just need combat to have a medieval Skyrim rimworld run and to mess around with one punch

**Comment by Alexis-Grimm** [comment]
All hard caps are removed by this mod already, I do not change the way these things are balanced however so things like soft caps from point process curves are unaffected. I may one day remove soft caps once I can figure out how to balance it, but as I've said multiple times, I do not currently have the time for this.
